export const SET_TRACKLIST = 'SET_TRACKLIST';
export const SET_CURRENT_LYRIC = 'SET_CURRENT_LYRIC';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH';
export const SET_LOADING = 'SET_LOADING';
export const SET_NOT_FOUND = 'SET_NOT_FOUND';